
<div class="md:w-[48rem] md:mx-auto md:text-lg lg:text-xl">

    <h1 class="text-3xl font-bold my-4 md:my-6 mx-1" id="why-practicing-meditation">Varför träna meditation?</h1>
    <p class="my-4 md:my-6 mx-1">Kort sagt så kan det förbättra ditt vardagliga liv.</p>
    <p class="my-4 md:my-6 mx-1">[I texten så nämner jag ordet <em>medvetenhet</em>. Med medvetenhet så menar jag att vara <em>aware</em> (eng.) eller <em>mindful</em>, vilket innebär att man vet vad det är som man upplever så detaljerat som möjligt. De orden betyder samma sak. Med medvetenhet menar jag inte att man är i vaket tillstånd (alltså att man inte sover).]</p>
    <p class="my-4 md:my-6 mx-1">De effekter som man kan få med meditation är ju väldigt subjektivt, men om man tränar meditation som grundar sig i att vara fokuserad på meditationsobjekt samt är medveten (eng. aware) över sina upplevelser (i sinnet) så kommer man att förbättra:</p>
    <ul class="pl-7 list-disc">
        <li>Sitt fokus. Förmågan att koncentrera eller stabilisera sinnet kring ett sinnesobjekt (känsla i kroppen, tankar, emotioner, smak, doft, hörsel, känsel och syn).</li>
        <li>Medvetenhet över sinnesobjekt. Att inte reagera på det man upplever är en sidoeffekt av att man är medveten.</li>
    </ul>
    <p class="my-4 md:my-6 mx-1">Värt att notera är att “inte reagera” innebär ju inte att man förtrycker sina upplevelser (tankar, känslor etc.). Att förhålla sig icke-reaktivt innebär att man klart och tydligt kan observera (vara medveten/att veta) det som sker inombords. Det innebär också att man kan känna sina tankar och känslor utan att trycka undan eller vilja ha mer av upplevelserna.</p>
    <p class="my-4 md:my-6 mx-1">Bara det att man har fokus och är mer medveten så blir man per automatik bättre på att hantera de situationer som sker i det vardagliga livet. För det första så är man mer lugn och bättre på att ta in det som sker i ens kropp när man har mediterat/mediterar. För det andra så reagerar man inte lika fort med stress och press när man upplever något i vardagen (positivt såsom negativt), vilket möjliggöra för mer genomtänkta beslut.</p>
    <h2 class="text-2xl font-bold my-3 mx-1" id="varför-man-inte-ska-meditera">Varför man inte ska meditera</h2>
    <p class="my-4 md:my-6 mx-1">Nu tycker ju jag att man ska träna meditation på grund av de positiva effekter som det ger. Men (djup) meditationsträning har en “mörk” sida och det är att det exponerar ditt medvetna för det omedvetna i sinnet. Det är ju svårt att veta att det omedvetna sinnet finns då den ju är omedveten, men man kan ganska lätt inse att det döljer sig något inom en själv genom att se hur man reagerar på olika situationer i det vardagliga livet. Rädsla är i min erfarenhet en tydlig reaktion på att någon omedveten tolkning av en situation har skett. Genom att ett yttre stimuli registreras i sinnet (medvetna) så triggar det igång något i kroppen och man kan känna sig rädd. Detta skulle jag säga är en reaktion från det omedvetna, vilket gör att man känner rädsla medvetet.</p>
    <p class="my-4 md:my-6 mx-1">När man mediterar så förblir man medveten över tid. Det innebär att man klart och tydligt kan se det som sker i sinnet och kroppen. Med ett stabilt sinne kring det som man upplever så upplever man klart och tydligt sinnesobjekten: Man kan se hur objekten uppstår (t.ex. vart i kroppen), hur de upplevs men också när de avtar. Detta sätt att förhålla sig till sina upplevelser skapar inga reaktioner (begär eller motvilja) utan man observerar/accepterar objekten för vad det är. Gör man detta över tid så kommer de omedvetna att bli mer medvetet av dig. Det innebär att emotioner såsom rädsla, sorg, glädje, etc. visar sig. Genom att uppleva dessa objekt fullt ut (medvetet, icke-reaktivt och med koncentration) så kommer dessa att “frigöras” från systemet (kroppen och sinnet).</p>
    <p class="my-4 md:my-6 mx-1">Så meditation handlar inte om att man ska hamna i ett euforiskt tillstånd (eller att upprätthålla något tillstånd alls), eller för den delen att hantera de negativa tankar/känslor som kan uppstå. Dessa är bara sidoeffekter av att man mediterar. Att meditera innebär att man upplever det som sker i både sinnet och kroppen objektivt (att vara medveten över/to be aware of); med andra ord så vet man vad man upplever klart och tydligt. Det finns inget mål med meditation eller att man ska uppnå något med att meditera utan meditation är ett förhållningssätt (eventuellt en livsstil) till det man upplever.</p>
    <h2 class="text-2xl font-bold my-3 mx-1" id="varför-ska-man-då-meditera">Varför ska man då meditera?</h2>
    <p class="my-4 md:my-6 mx-1">Jag kan ju tyvärr inte svara för din del. Personligen så har meditationen definitivt förbättrat mitt vardagliga liv även om det inte är målet med meditation (utan det är bara en sidoeffekt av den). Personligen så har ju meditation hjälpt mig med många emotionella utmaningar som man har haft genom åren. Jag kan definitivt säga att mitt liv skulle vara mycket värre om jag inte hade mediterat. Det i sig säger ganska mycket om hur värdefull denna förmåga är att ha!</p>
    <h2 class="text-2xl font-bold my-3 mx-1" id="meditation-och-kampsportsträning">Meditation och kampsportsträning</h2>
    <p class="my-4 md:my-6 mx-1">Kampsportsträningen (all träning för den delen) gynnas av ett skarpt fokus på det som sker i kroppen just nu. Meditation med mer tyngd på koncentrationsbiten kan ge ett skarpare fokus och stänga bort distraktioner. I tävlingssammanhang (eller i andra pressade situationer) är det väldigt gynnsamt att kunna fokusera samt ha ett klart sinne och inte distraheras av omgivningen. I ett meditativt tillstånd eller direkt efter ett meditativt tillstånd så är kroppen väldigt avslappnat och inte stressat, vilket definitivt hjälper i träningen.</p>
    <p class="my-4 md:my-6 mx-1">I träningen som vi kör på wushulin så ägnar vi de sista 10 minuterna till att meditera genom att fokusera på kroppens förnimmelser samt på andningen. Vill man lära sig mer om meditation så är det bra att komma på ett träningspass.</p>

</div>